{% set name = "bayespy" %}
{% set version = "0.5.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c16cdc73bbcd9a1124a0495056065b7ce938dbe6c2c780dc330c83fb4d2640a

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - h5py
    - numpy >=1.10.0
    - python >=3
    - scipy >=0.13.0
    - matplotlib-base
    - ipython >=7.7

test:
  imports:
    - bayespy
    - bayespy.demos
    - bayespy.inference
    - bayespy.inference.vmp
    - bayespy.inference.vmp.nodes
    - bayespy.inference.vmp.nodes.tests
    - bayespy.inference.vmp.tests
    - bayespy.nodes
    - bayespy.tests
    - bayespy.utils
    - bayespy.utils.covfunc
    - bayespy.utils.tests

about:
  home: http://bayespy.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Variational Bayesian inference tools for Python
  description: |
    BayesPy provides tools for Bayesian inference with Python. The user constructs a model as a Bayesian network, 
    observes data and runs posterior inference. The goal is to provide a tool which is efficient, flexible and 
    extendable enough for expert use but also accessible for more casual users.

    Currently, only variational Bayesian inference for conjugate-exponential family (variational message passing) 
    has been implemented. Future work includes variational approximations for other types of distributions and 
    possibly other approximate inference methods such as expectation propagation, Laplace approximations, 
    Markov chain Monte Carlo (MCMC) and other methods. Contributions are welcome.
  doc_url: http://bayespy.org/
  dev_url: https://github.com/bayespy/bayespy

extra:
  recipe-maintainers:
    - volpatto
